Training the TuckER model...
Number of training data points: 544230
Let's use 4 GPUs!
Starting training...
Traceback (most recent call last):
  File "main.py", line 208, in <module>
    experiment.train_and_eval()
  File "main.py", line 141, in train_and_eval
    predictions = model.forward(e1_idx, r_idx)
  File "/usr/common/software/pytorch/v1.5.1-gpu/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/common/software/pytorch/v1.5.1-gpu/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/common/software/pytorch/v1.5.1-gpu/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/usr/common/software/pytorch/v1.5.1-gpu/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/usr/common/software/pytorch/v1.5.1-gpu/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/usr/common/software/pytorch/v1.5.1-gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/global/u1/v/vbharadw/TuckER/model.py", line 122, in forward
    x = self.bn0(e1)
  File "/usr/common/software/pytorch/v1.5.1-gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/common/software/pytorch/v1.5.1-gpu/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 106, in forward
    exponential_average_factor, self.eps)
  File "/usr/common/software/pytorch/v1.5.1-gpu/lib/python3.7/site-packages/torch/nn/functional.py", line 1923, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 0 does not equal 1 (while checking arguments for cudnn_batch_norm)

